config/routes.rb
Rails.application.routes.draw do

  get 'sessions/create'

  get 'sessions/destroy'

  get 'home/show'

  root 'cities#search'

  get '/show', to: 'cities#show'
  post '/show', to: 'cities#show'

  get '/about', to: 'cities#about', as: 'about'

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :home, only: [:show]

  get '/profile', to: 'cities#profile', as: 'profile'

  get '/save_city', to: 'cities#save_city'
  post '/save_city', to: 'cities#save_city'

end

app/models/city.rb
class City < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	def self.from_omniauth(auth)
   	where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

  has_many :cities
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
	include CitiesHelper

	def search
		@search = ""
	end
	def show
		# binding.pry
		@city = params[:city_name]

		if params[:city_name] == nil
			@city = params[:format]
		end

		if params[:search_text]
			@search_text = params[:search_text]
		else
			@search_text = ''
		end

		@weather = get_weather(@city)
		@events = get_events(@city, @search_text)
		@fave_city = ''
	end
	def about
	end
	def profile
		@new_city = params[:format]
		# 
		@cities = current_user.cities
	end

	def save_city
		@fave_city = params[:fave_city]
		# 
		City.create(name: @fave_city, user_id: current_user.id)
		redirect_to profile_path(@fave_city)
	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def show
  	
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
	require 'open-uri'
	require 'json'
	def get_weather(city_name)
		search_url = "http://api.openweathermap.org/data/2.5/weather?q={" + city_name + "}"
		result = JSON.parse(open(search_url).read)
		return result
	end

	def get_events(city_name, search_text)
		city_name.gsub!(' ','+')
		search_text.gsub!(' ','+')
		search_url = "http://api.eventful.com/json/events/search?&app_key=" + ENV["eventful_key"]+ "&location=" + city_name + "&date=Today&keywords=" + search_text
		result = JSON.parse(open(search_url).read)
		return result
	end

	def kelvin_to_faren(temp)
		temp = temp.to_i
		temp * 9/5 - 459
	end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/cities/_filter.html.erb
<div class="filter">
  <%= form_tag show_path, method: :get, class: "form-inline" do %>

    <div class="row">
      <div class="col-md-4">
        <%= label_tag "location" %>
      </div>
      <div class="col-md-5">
        <%= label_tag 'search events' %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-4">
        <%= text_field_tag :city_name, params[:city_name], placeholder: "location", class: "form-control input-sm", size: 40 %>
      </div>
      <div class="col-md-5">  
        <%= text_field_tag :search_text, params[:search_text], placeholder: "search", class: "form-control input-sm", size: 50 %>
      </div>
      <div class ="col-md-2">
        <%= submit_tag "Search", name: nil, class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>
</br>

app/views/cities/about.html.erb
<div class="container">
	<div class='well text-center'> 

		<h2>about this site</h2>
		</br>
		<p>This site allows a user to input a city name and get today's weather and events for that city. The site uses the open weather map api for the weather information, and the eventful api for the event information.</p>

	</div>
</div>

app/views/cities/profile.html.erb
<div class="container">
	<div class='well text-center'> 

		<h2>Profile for <%= current_user.name %></h2>

		<h4>My Favorite Cities:</h4>
		<% @cities.each do |c| %>
			<p><%= link_to c.name, show_path(c.name) %></p>
		<% end %>

	</div>
<div>

app/views/cities/search.html.erb
<div style="text-align:center;">
	</br>
	<%= form_for(@search, url: { action: 'show' }) do |f| %>
		<h1 style="color:white;">Search Weather and Events In:</h1>
		</br>
		<p><%= f.text_field :city_name, :size => 40 %></p>
		</br>
		<p><%= f.submit 'search', class: "btn btn-primary" %></p>
	<% end %>
</div>

app/views/cities/show.html.erb
<div class="container">
	<div class='well text-center'> 
		<h2>Current Weather Forecast for <%= @weather['name'] %></h2>
		</br>
		<div class="row">
      <div class="col-md-4">
					<p><strong>City Name:</strong> <%= @weather['name'] %>, <%= @weather['country'] %></p>
					<p><strong>Forecast:</strong> <%= @weather['weather'][0]['main'] %></p>
					<p><strong>Description:</strong> <%= @weather['weather'][0]['description'] %></p>
      </div>
      <div class="col-md-4">
					<p><strong>Current Temp:</strong> <%= kelvin_to_faren(@weather['main']['temp']) %> deg F</p>
					<p><strong>Pressure:</strong> <%= @weather['main']['pressure'] %> hPa</p>
					<p><strong>Humidity:</strong> <%= @weather['main']['humidity'] %> %</p>
      </div>
      <div class="col-md-4">
					<p><strong>Min Temp:</strong> <%= kelvin_to_faren(@weather['main']['temp_min']) %> deg F</p>
					<p><strong>Max Temp:</strong> <%= kelvin_to_faren(@weather['main']['temp_max']) %> deg F</p>

					<p><strong>Wind Speed:</strong> <%= @weather['wind']['speed'] %> m/sec</p>
					<p><strong>Wind Direction:</strong> <%= @weather['wind']['deg'] %> deg</p>			
			</div>
    </div>

	  <% if current_user %>
			</br>
			<%= form_for(@fave_city, url: { action: 'save_city' }) do |f| %>
				<%= f.hidden_field :fave_city, :value => @weather['name'] %>
				</br>
				<p><%= f.submit 'save city as favorite', class: "btn btn-primary" %></p>
			<% end %>
		<% end %>
	</div>

	<div class='well text-center'> 
		<%= render 'cities/filter' %>
	</div>

	<div class='well text-left'> 
		<h2 style="text-align:center;">Today's Events in <%= @weather['name'] %></h2>
		</br>
		</br>
		<% if @events['events'] %>
			<% @events['events']['event'].each do |e| %>
				<h3><%= e['title'] %></h3>
				<p><%= e['start_time'] %> to <%= e['stop_time'] %></p>	
				<p><strong><%= e['venue_name'] %></strong></p>
				<p><strong><%= e['venue_address'] %></strong></p>
				<p><strong><%= e['city_name'] %>, <%= e['region_abbr'] %></strong></p>
				<p><%= e['description'].html_safe %></p>
				</br>
			<% end %>
		<% else %>
			<h3>Sorry, could not find any events for that city! Please search again.</h3>
		<% end %>
	</div>
</div>

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container" style="color:white;">
  </br>
	</br>
    <p class="footer-block">Copyright 2015 CitySearch</p>	
    <p>About   Privacy Policy   Terms/Conditions</p>
  </br>
 	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to 'CitySearch', root_path, class: 'brand' %>
    </div>
    <div>
      <ul class="nav navbar-nav pull-right">
 
        <% if current_user %>
          <li><p style="color:black;">Signed in as <strong><%= current_user.name %></strong></p></li>
          <li><%= link_to 'home', root_path, style: "color:white;" %></li>
          <li><%= link_to 'about', about_path, style: "color:white;" %></li>
          <li><%= link_to 'my profile', profile_path, style: "color:white;" %></li>
          <li><%= link_to "Sign out", signout_path, id: "sign_out", style: "color:white;" %></li>
        <% else %>
          <li><%= link_to 'home', root_path, style: "color:white;" %></li>
          <li><%= link_to 'about', about_path, style: "color:white;" %></li>
          <li><%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in", style: "color:white;" %></li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Citysearch</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <%= render 'layouts/header' %>
    </div>
  </div>
</div>

<div id="central-body">
  <%= yield %>
</div>

<%= render 'layouts/footer' %>


</body>
</html>